name: Release

on:
  push:
    branches:
          - main  # Trigger on any push to the main branch
  pull_request:
  workflow_dispatch:  # Allow manual triggers

jobs:
  armbian-images:
    name: '2025 Realsense Image Build'
    runs-on: ubuntu-22.04-arm  # Use a GitHub-hosted runner
    
    strategy:
      matrix:
        board: [rock-5c, radxa-zero3]
  
    steps:
      # Checkout this repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Checkout the Armbian build repository
      - name: Checkout Armbian Build Repository
        uses: actions/checkout@v3
        with:
          repository: armbian/build
          ref: main  # Use the main branch of the Armbian repository
          path: armbian-build  # Check out the Armbian repository to this subdirectory

      - name: Copy Userpatches
        run: |
          mkdir -p armbian-build/userpatches
          cp -r 2025/realsense/* armbian-build/userpatches/
        working-directory: ${{ github.workspace }}

      - name: Build Armbian Image
        run: |
          ./compile.sh build BOARD=${{ matrix.board }} ENABLE_EXTENSIONS=preset-firstrun BRANCH=vendor BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE=jammy
        working-directory: ${{ github.workspace }}/armbian-build
      
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.board }}-jammy-realsense-${{ github.sha }}.img
          path: ${{ github.workspace }}/armbian-build/output/images/*.img
      
