name: Build Images

on:
  push:
    branches:
      - main  # Trigger on any push to the main branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  armbian-images:
    runs-on: ubuntu-22.04-arm  # Use a GitHub-hosted runner
    steps:
      # Checkout this repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Checkout the Armbian build repository
      - name: Checkout Armbian Build Repository
        uses: actions/checkout@v3
        with:
          repository: armbian/build
          ref: main  # Use the main branch of the Armbian repository
          path: armbian-build  # Check out the Armbian repository to this subdirectory

      - name: Copy Userpatches
        run: |
          mkdir -p armbian-build/userpatches
          cp -r 2025/realsense/customize-image.sh armbian-build/userpatches/
        working-directory: ${{ github.workspace }}

      - name: Build Armbian Image
        run: |
          ./compile.sh build BOARD=rock-5c BRANCH=vendor BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE=jammy COMPRESS_OUTPUTIMAGE=sha,gz
        working-directory: ${{ github.workspace }}/armbian-build
      
      - name: Compress and Archive Output Image
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          for img in ${{ github.workspace }}/armbian-build/output/images/*.img; do
            gzip -c "$img" > "${img}.gz"
            mv "${img}.gz" ${{ github.workspace }}/artifacts/
          done

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: armbian-images
          path:  ${{env.GITHUB_WORKSPACE}}/artifacts
